Light/Dark Mode 초기 작업
elice-study-3rd/country-search-app pull request #4
Opened 2023-10-17 08:53 UTC by Normaljun95

## 설명
버튼을 이용해 APP 테마 (Light / Dark Mode) 변경 함수 작성
- 1차 작업

## 작업사항
- [ ] Header 부분 Dark Mode 버튼 디자인 구현 (60%)
- [ ] Light / Dark Mode 에 따라 CSS 작업 (30%)

## 기타 사항
메인 UI 담당자와 Header 및 CSS 협업 관련 논의 필요
- '하나의 파일에서 공동으로 진행' or '별개의 파일을 작성하여 연동하여 진행'

2023-10-17 14:47 UTC, Ji-hoon requested changes
고생하셨습니다. 👍  light-theme 클래스 지정 위치만 검토 부탁드려요.

2023-10-17 14:47 UTC, Ji-hoon commented on src/Header.js
> +        })
테마 변경 시에 헤더 뿐만아니라 페이지의 모든 요소가 영향을 받을 텐데, light-theme 같은 클래스는 header 요소에 지정하기 보다는 상위의 요소에 할당하는게 더 나을 것 같아보입니다. (body나 html, 또는 .App 또는 #root)

2023-10-17 14:47 UTC, Ji-hoon commented on src/Header.js
> +                <i className="fas fa-moon" onClick={() => changeTheme()}></i>Dark Mode
기본이 Dark Mode이고, 버튼 클릭 시 Light Mode로 변경된다면 아이콘이나 레이블도 다르게 표시되는 피드백이 있다면 사용자가 인식하기 더 쉬울 것 같습니다. ( 예시 : Dark Mode & fa-moon <=> Light Mode & fa-sun )

2023-10-18 02:08 UTC, Normaljun95 commented on src/Header.js
> +        })
test 에서 위와 같은 방법으로 모든 요소에 동작이 되도록 구현은 했는데, 요청하는 파일들을 나누다보니 확실히 동작에 대한 delay가 header 따로 body 따로 되는 문제가 발생했습니다. 말씀하신 상위 요소에 할당하여 문제 해결해보겠습니다! 감사합니다!

2023-10-18 07:04 UTC, merged